### ISSUE TITLE
RFC's

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3fairness#1]
Add to `attic` folder
- for Metric
- Debiasing Method
- Visualizations

**Comment by pfistfl** [comment]
https://github.com/mlr-org/mlr3temporal/tree/main/attic

**Comment by pfistfl** [comment]
For the RFC's create a single PR for each RFC with the `.md` file in the `attic` folder

**Comment by superp0tat0** [comment]
Splitted to subissues
