### ISSUE TITLE
Add toy datasets

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3fairness#2]

**Comment by pfistfl** [comment]
Create a version of the compas dataset that is 1) fully numeric and 2) does not have missing values.

**Comment by pfistfl** [comment]
Adult: https://github.com/pfistfl/mcboost/blob/342301bc015c04bb98633c4f4d3f9047f963e157/vignettes/mcboost_basics_extensions.Rmd#L50

**Comment by superp0tat0** [comment]
Finished as subissues
