### ISSUE TITLE
Aequitas Fairness Report

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3fairness#53]
http://aequitas.dssg.io/example.html

Cite and see what is useful

**Comment by pfistfl** [comment]
- [ ] General Task Documentation: number of obs, features, what is prot. att. etc. [20%]
- [ ] Short summary [5%]
- [ ] Exploratory Data Analysis  [20%]
- [ ] Fairness Metrics & Visualizations [35%]
- [ ] Interpretability [20%]

**Comment by superp0tat0** [comment]
sorry, working on it

**Comment by pfistfl** [comment]
Done in #55
